version: '2.1'
services:
    nginx:
        image: 'nginx:stable-alpine'
        depends_on:
            - engine
        volumes:
            - './infrastructure/nginx/entrypoint.bash:/entrypoint.bash:ro'
            - './infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        volumes_from:
            - 'engine:ro'
        entrypoint: /entrypoint.bash
        ports:
            - '43080:80'
    engine:
        image: 'bitnami/php-fpm:latest'
        volumes:
          - './:/usr/share/nginx/html/'
    varnish:
        image: varnish
        volumes:
          - './infrastructure/varnish/default.vcl:/etc/varnish/default.vcl:ro'
        ports:
            - '43082:80'
        depends_on:
            - nginx

